export const API_DUMMY_DATA = [
  {
    _id: "1",
    title: "Hello World",
    created: "01/08/20",
    modified: "02/08/20",
    content: "This is the First Dummy Note!",
    favourite: [1, 2, 3],
    tags: ["games", "daily", "tasks"],
    access: [1, 2, 3],
  },
  {
    _id: "2",
    title: "Hello World",
    created: "01/08/20",
    modified: "02/08/20",
    content: "This is the First Dummy Note!",
    favourite: [1, 2, 3],
    tags: ["dev", "code"],
    access: [1, 2, 3],
  },
  {
    _id: "3",
    title: "Hello World",
    created: "01/08/20",
    modified: "02/08/20",
    content: "This is the First Dummy Note!",
    favourite: [1, 2, 3],
    tags: ["food", "menu", "tasty"],
    access: [1, 2, 3],
  },
  {
    _id: "4",
    title: "Hello World",
    created: "01/08/20",
    modified: "02/08/20",
    content: "This is the First Dummy Note!",
    favourite: [1, 2, 3],
    tags: ["explore", "discover", "watch"],
    access: [1, 2, 3],
  },
  {
    _id: "5",
    title: "Hello World",
    created: "01/08/20",
    modified: "02/08/20",
    content: "This is the First Dummy Note!",
    favourite: [1, 2, 3],
    tags: ["dev", "code", "view"],
    access: [1, 2, 3],
  },
  {
    _id: "6",
    title: "Hello World",
    created: "01/08/20",
    modified: "02/08/20",
    content: "This is the First Dummy Note!",
    favourite: [1, 2, 3],
    tags: ["tag#1", "tag#2", "tag#3"],
    access: [1, 2, 3],
  },
];
